### PR TITLE
chore: bump node versions

### PR DESCRIPTION
**Pull request by raisedadead**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Review by ShaunSHamilton — COMMENTED** [review]
Silly question: Is this ok?

I notice we have:
```yml
uses: actions/setup-node@v3
```

And I can see [`setup-node`](https://github.com/actions/setup-node/releases) have (since 24/02/2022) released v3, but they do not document it anywhere

**Comment by raisedadead** [comment]
Yup we got on v3 via https://github.com/freeCodeCamp/crowdin-config/commit/5fba1579a44a5d65abbf530b1273cbd5b97fe017

Their release page is all you get about the changes. 

They introduced a couple of breaking changes, one of which we already are compliant with (the use of `node-version`), and the other thing is we need to move to the latest Node versions (16), which this PR does.

So we should be OK - unless that's not what you are confirming?

**Review by ShaunSHamilton — APPROVED** [review]
> So we should be OK - unless that's not what you are confirming?

That is exactly what I was confirming. Thank you 👍

**Comment by nhcarrigan** [comment]
Just for clarification sake...

The version of node here only impacts our test running environment for the QA checks. The *actual* QA checks running on Crowdin run in a severely outdated environment (doesn't even support ES6).

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
